### ISSUE TITLE
[FR]: Adjust background image darkening

### ISSUE THREAD

**Issue by oerix** [LesTR/homeassistant-minimalistic-area-card#147]
### What happened?

Would it be possible to add an option to adjust the dimming of the background image?  

e.g. `darken_image: 50` would be the opacity percentage.

I'm not sure if this possible using card_mod, but would be nice if I could easily adjust it within the card yaml.

Thanks

### Card Version

1.2.18

### HomeAssistant Version

2024.12.2

### Relevant card config

```yaml
darken_image:
```

**Comment by LesTR** [comment]
I think you can do this by card_mod, 
smt like:
```
.darken {
        filter: brightness(<your value>) !important;
 }
```

Currently, I don't have an easy way to customize CSS in runtime, but I can take a look at it when I have some free time.
