### ISSUE TITLE
[Bug]: This does not work

### ISSUE THREAD

**Issue by Triskelen** [LesTR/homeassistant-minimalistic-area-card#28]
### What happened?

i installed the fork like instructed in my previous post and it worked like a charm. 
added the code to change the color and it does not work when i press save it even deletes the added code.

### Card Version

1.2.4

### Home Assistant Version

2024.8.1

### Browser Version

chrome 127.0.6533.100

**Comment by LesTR** [comment]
@Triskelen  Hmm, I have no idea how to help you; it works for me. Can you share your YAML? Do you see any errors in the JS console?

**Comment by LesTR** [comment]
@Triskelen, why are you opening some issues and then don't react? Closing...

**Comment by Triskelen** [comment]
My sincere apologies for any inconvenience caused. Unfortunately, my one-year-old daughter is currently hospitalized, and the situation requires my undivided attention. As a result, I have limited capacity to focus on other matters at this time. I kindly request your understanding and patience in this regard.

**Comment by LesTR** [comment]
ouu, sorry to hear that. Hopefully she will be better soon 🤞
