### ISSUE TITLE
[Question]: how do i use this fork ?

### ISSUE THREAD

**Issue by Triskelen** [LesTR/homeassistant-minimalistic-area-card#3]
### What happened?

i would like to know how to install the forked version with the state colours

### Card Version

1.2.0

### HomeAssistant Version

latest

### Relevant log output

```shell
none
```

**Comment by LesTR** [comment]
In hacs select `custom repositories`

<img width="964" alt="image" src="https://github.com/user-attachments/assets/f2520148-fd11-45ca-bed8-4af563353ed1">


Add it like this:


<img width="400" alt="image" src="https://github.com/user-attachments/assets/dfa2b26e-4a08-4d5e-b928-567849703603">


Now you should be able to find it:
<img width="596" alt="image" src="https://github.com/user-attachments/assets/d8d70024-705f-4e5c-8a7f-c854556791c1">


Just make sure it's from my fork:
<img width="381" alt="image" src="https://github.com/user-attachments/assets/517aa1b0-4a20-4ce9-9a1f-d465c459c0f2">

**Comment by LesTR** [comment]
I hope your question was answered. I'm closing this issue; feel free to comment/reopen it if you need to.
