### ISSUE TITLE
[Question]: Entity visibility based on state

### ISSUE THREAD

**Issue by ikomtur** [LesTR/homeassistant-minimalistic-area-card#39]
### What happened?

Is it possible to add such option? It would be nice to show the icons depending on its state. E.g. motion icon only if there is a motion.

### Card Version

1.2.5

### HomeAssistant Version

2024.8.3

**Comment by LesTR** [comment]
Hmm, I was thinking about something similar. For example, here in the kitchen, I have two water leak sensors
<img width="256" alt="image" src="https://github.com/user-attachments/assets/6cf3b0fc-538f-43c5-85eb-f92b3645f540">

It will be good to have an option to hide them in case of dry value.

**Comment by LesTR** [comment]
Fixed in https://github.com/LesTR/homeassistant-minimalistic-area-card/releases/tag/v1.2.7

**Comment by LesTR** [comment]
@ikomtur BTW from [v1.2.9 ](https://github.com/LesTR/homeassistant-minimalistic-area-card/releases/tag/v1.2.9) you should be able to use the template like this, instead of state override.
```
entities:
  - entity: binary_sensor.dishwasher_water_leakage_sensor_moisture
     hide: ${return state != "on"}
```
